export const PRICE_LOW_TO_HIGH = 'PRICE_LOW_TO_HIGH';
export const PRICE_HIGH_TO_LOW = 'PRICE_HIGH_TO_LOW';
export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';
export const SEARCH_KEYWORD_REQUEST = 'SEARCH_KEYWORD_REQUEST';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';